name: 'git-tag-check-action'
description: 'Check git tag is exists or not'
author: 'bbonkr'
inputs:
  TAG: 
    required: true
    description: 'Tag'
  GITHUB_TOKEN:
    required: true
    description: 'GitHub repository Access token'
  OWNER:
    required: false
    description: 'Name of repository owner'
    default: ''
  REPO:
    required: false
    description: 'Repository name'
    default: ''
outputs:
  hasTag:
    description: 'Tag is exists or not'
runs:
  using: 'node12'
  main: 'dist/index.js'
