name: 'git-tag-check-action'
description: 'Check git tag is exists or not'
author: 'bbonkr'
branding:
  color: purple 
  icon: check
inputs:
  tag: 
    required: true
    description: 'Tag'
  github_token:
    required: true
    description: 'GitHub Personal Access Token. It requires REPO scope.'
  owner:
    required: false
    description: 'Name of repository owner'
    default: 'For test. You does not need this input.'
  repo:
    required: false
    description: 'Repository name'
    default: 'For test. You does not need this input.'
outputs:
  tag:
    description: 'If tag is exists, returns tag. Does not exist then empty string.'
runs:
  using: 'node12'
  main: 'dist/index.js'
