name: create release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]+.[0-9]+" # v1.0.0-alpha.1

jobs:
  release:
    name: create release 
    runs-on: ubuntu-latest
    steps:
      - name: Release 
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          version: ${{ github.ref_name }}
          publish: true 
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
