name: create release
on:
  push:
    tags:
      # v1.0.0
      - '^v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$'

jobs:
  release:
    name: create release 
    runs-on: ubuntu-latest
    steps:
      - name: Release 
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          version: ${{ github.ref_name }}
          publish: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
