name: 'create-tag'

on:
  push:
    branches:
      - main 
    tags:
      - "!*"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
        
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x        

      - run: |
          npm install

      - run: |
          npm run all
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OWNER: ${{ secrets.OWNER }}
          REPO: ${{ secrets.REPO }} 

      - name: get version 
        uses: bbonkr/get-version-action@v1
        id: get_version
        with:
         project: package.json

      - name: check tag exists
        uses: ./
        id: check_tag
        with:
          tag: "v${{ steps.get_version.outputs.version }}"
          github_token: ${{ secrets.GH_TOKEN }}

      - name: Create tag current
        uses: rickstaa/action-create-tag@v1
        if: ${{ steps.check_tag.outputs.tag == '' }}
        with:
          tag: "v${{ steps.get_version.outputs.version }}"
          message: "v${{ steps.get_version.outputs.version }}"
          commit_sha: ${{ github.sha }}

      - name: Create or update tag major
        uses: rickstaa/action-create-tag@v1
        if: ${{ (steps.check_tag.outputs.tag == '') && (steps.get_version.outputs.major != '') }}
        with:
          tag: "v${{ steps.get_version.outputs.major }}"
          message: "v${{ steps.get_version.outputs.major }}"
          commit_sha: ${{ github.sha }}
          force_push_tag: true 

      - name: Create or update tag major.minor
        uses: rickstaa/action-create-tag@v1
        if: ${{ (steps.check_tag.outputs.tag == '') && (steps.get_version.outputs.major != '') && (steps.get_version.outputs.minor != '') }}
        with:
          tag: "v${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}"
          message: "v${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}"
          commit_sha: ${{ github.sha }}
          force_push_tag: true 

      - name: Create or update latest 
        uses: rickstaa/action-create-tag@v1
        if: ${{ (steps.check_tag.outputs.tag == '') }}
        with:
          tag: latest
          message: latest
          commit_sha: ${{ github.sha }}
          force_push_tag: true       

      - name: git tag skipped
        if: ${{ steps.check_tag.outputs.tag != '' }}
        run: |
          echo "Tag (${{ steps.check_tag.outputs.tag }}) is exists already." 
